/**
 *
 * @file   z80tab.c 
 * @date   16.03.2018 
 * @license This project is released under the GPL 2 license.
 * @brief Main instruction table
 *
 */

#include "z80tab.h"

/**
 * sorted table for binary search algo, sorted by mnemo field
 */


/* give space for zero entry */
const opcode_table opcode_tab[]=
{
	{	.opcode=0xED,	.mnemo="****"	},
	{	.opcode=0xDDCB,	.mnemo="****"	},
	{	.opcode=0xFDCB,	.mnemo="****"	},
	{	.opcode=0xFD,	.mnemo="****"	},
	{	.opcode=0xDD,	.mnemo="****"	},
	{	.opcode=0xCB,	.mnemo="****"	},
	{	.opcode=0xCE,	.mnemo="ADC A, %#.2x",	.data_size=1	},
	{	.opcode=0x8E,	.mnemo="ADC A, [HL]"	},
	{	.opcode=0xDD8E,	.mnemo="ADC A, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD8E,	.mnemo="ADC A, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x8F,	.mnemo="ADC A, A"	},
	{	.opcode=0x88,	.mnemo="ADC A, B"	},
	{	.opcode=0x89,	.mnemo="ADC A, C"	},
	{	.opcode=0x8A,	.mnemo="ADC A, D"	},
	{	.opcode=0x8B,	.mnemo="ADC A, E"	},
	{	.opcode=0x8C,	.mnemo="ADC A, H"	},
	{	.opcode=0x8D,	.mnemo="ADC A, L"	},
	{	.opcode=0xDD8C,	.mnemo="ADC A, XH"	},
	{	.opcode=0xDD8D,	.mnemo="ADC A, XL"	},
	{	.opcode=0xFD8C,	.mnemo="ADC A, YH"	},
	{	.opcode=0xFD8D,	.mnemo="ADC A, YL"	},
	{	.opcode=0xED4A,	.mnemo="ADC HL, BC"	},
	{	.opcode=0xED5A,	.mnemo="ADC HL, DE"	},
	{	.opcode=0xED6A,	.mnemo="ADC HL, HL"	},
	{	.opcode=0xED7A,	.mnemo="ADC HL, SP"	},
	{	.opcode=0xC6,	.mnemo="ADD A, %#.2x",	.data_size=1	},
	{	.opcode=0x86,	.mnemo="ADD A, [HL]"	},
	{	.opcode=0xDD86,	.mnemo="ADD A, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD86,	.mnemo="ADD A, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x87,	.mnemo="ADD A, A"	},
	{	.opcode=0x80,	.mnemo="ADD A, B"	},
	{	.opcode=0x81,	.mnemo="ADD A, C"	},
	{	.opcode=0x82,	.mnemo="ADD A, D"	},
	{	.opcode=0x83,	.mnemo="ADD A, E"	},
	{	.opcode=0x84,	.mnemo="ADD A, H"	},
	{	.opcode=0x85,	.mnemo="ADD A, L"	},
	{	.opcode=0xDD84,	.mnemo="ADD A, XH"	},
	{	.opcode=0xDD85,	.mnemo="ADD A, XL"	},
	{	.opcode=0xFD84,	.mnemo="ADD A, YH"	},
	{	.opcode=0xFD85,	.mnemo="ADD A, YL"	},
	{	.opcode=0x09,	.mnemo="ADD HL, BC"	},
	{	.opcode=0x19,	.mnemo="ADD HL, DE"	},
	{	.opcode=0x29,	.mnemo="ADD HL, HL"	},
	{	.opcode=0x39,	.mnemo="ADD HL, SP"	},
	{	.opcode=0xDD09,	.mnemo="ADD IX, BC"	},
	{	.opcode=0xDD19,	.mnemo="ADD IX, DE"	},
	{	.opcode=0xDD29,	.mnemo="ADD IX, IX"	},
	{	.opcode=0xDD39,	.mnemo="ADD IX, SP"	},
	{	.opcode=0xFD09,	.mnemo="ADD IY, BC"	},
	{	.opcode=0xFD19,	.mnemo="ADD IY, DE"	},
	{	.opcode=0xFD29,	.mnemo="ADD IY, IY"	},
	{	.opcode=0xFD39,	.mnemo="ADD IY, SP"	},
	{	.opcode=0xE6,	.mnemo="AND %#.2x",	.data_size=1	},
	{	.opcode=0xA6,	.mnemo="AND [HL]"	},
	{	.opcode=0xDDA6,	.mnemo="AND [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDA6,	.mnemo="AND [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xA7,	.mnemo="AND A"	},
	{	.opcode=0xA0,	.mnemo="AND B"	},
	{	.opcode=0xA1,	.mnemo="AND C"	},
	{	.opcode=0xA2,	.mnemo="AND D"	},
	{	.opcode=0xA3,	.mnemo="AND E"	},
	{	.opcode=0xA4,	.mnemo="AND H"	},
	{	.opcode=0xA5,	.mnemo="AND L"	},
	{	.opcode=0xDDA4,	.mnemo="AND XH"	},
	{	.opcode=0xDDA5,	.mnemo="AND XL"	},
	{	.opcode=0xFDA4,	.mnemo="AND YH"	},
	{	.opcode=0xFDA5,	.mnemo="AND YL"	},
	{	.opcode=0xCB46,	.mnemo="BIT 0, [HL]"	},
	{	.opcode=0xDDCB46,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB45,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB47,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB43,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB44,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB42,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB41,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB40,	.mnemo="BIT 0, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB46,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB47,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB43,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB44,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB45,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB42,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB41,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB40,	.mnemo="BIT 0, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB47,	.mnemo="BIT 0, A"	},
	{	.opcode=0xCB40,	.mnemo="BIT 0, B"	},
	{	.opcode=0xCB41,	.mnemo="BIT 0, C"	},
	{	.opcode=0xCB42,	.mnemo="BIT 0, D"	},
	{	.opcode=0xCB43,	.mnemo="BIT 0, E"	},
	{	.opcode=0xCB44,	.mnemo="BIT 0, H"	},
	{	.opcode=0xCB45,	.mnemo="BIT 0, L"	},
	{	.opcode=0xCB4E,	.mnemo="BIT 1, [HL]"	},
	{	.opcode=0xDDCB4E,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB4C,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB4D,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB4F,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB4B,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB4A,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB49,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB48,	.mnemo="BIT 1, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB4E,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB4C,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB4D,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB4F,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB4A,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB4B,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB49,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB48,	.mnemo="BIT 1, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB4F,	.mnemo="BIT 1, A"	},
	{	.opcode=0xCB48,	.mnemo="BIT 1, B"	},
	{	.opcode=0xCB49,	.mnemo="BIT 1, C"	},
	{	.opcode=0xCB4A,	.mnemo="BIT 1, D"	},
	{	.opcode=0xCB4B,	.mnemo="BIT 1, E"	},
	{	.opcode=0xCB4C,	.mnemo="BIT 1, H"	},
	{	.opcode=0xCB4D,	.mnemo="BIT 1, L"	},
	{	.opcode=0xCB56,	.mnemo="BIT 2, [HL]"	},
	{	.opcode=0xDDCB56,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB54,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB55,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB57,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB52,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB53,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB51,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB50,	.mnemo="BIT 2, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB56,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB55,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB57,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB52,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB54,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB53,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB51,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB50,	.mnemo="BIT 2, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB57,	.mnemo="BIT 2, A"	},
	{	.opcode=0xCB50,	.mnemo="BIT 2, B"	},
	{	.opcode=0xCB51,	.mnemo="BIT 2, C"	},
	{	.opcode=0xCB52,	.mnemo="BIT 2, D"	},
	{	.opcode=0xCB53,	.mnemo="BIT 2, E"	},
	{	.opcode=0xCB54,	.mnemo="BIT 2, H"	},
	{	.opcode=0xCB55,	.mnemo="BIT 2, L"	},
	{	.opcode=0xCB5E,	.mnemo="BIT 3, [HL]"	},
	{	.opcode=0xDDCB5E,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB5D,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB5F,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB5B,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB5C,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB5A,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB59,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB58,	.mnemo="BIT 3, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB5E,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB5D,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB5F,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB5B,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB5C,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB5A,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB59,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB58,	.mnemo="BIT 3, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB5F,	.mnemo="BIT 3, A"	},
	{	.opcode=0xCB58,	.mnemo="BIT 3, B"	},
	{	.opcode=0xCB59,	.mnemo="BIT 3, C"	},
	{	.opcode=0xCB5A,	.mnemo="BIT 3, D"	},
	{	.opcode=0xCB5B,	.mnemo="BIT 3, E"	},
	{	.opcode=0xCB5C,	.mnemo="BIT 3, H"	},
	{	.opcode=0xCB5D,	.mnemo="BIT 3, L"	},
	{	.opcode=0xCB66,	.mnemo="BIT 4, [HL]"	},
	{	.opcode=0xDDCB66,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB67,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB63,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB64,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB65,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB62,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB61,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB60,	.mnemo="BIT 4, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB66,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB67,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB63,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB64,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB65,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB62,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB61,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB60,	.mnemo="BIT 4, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB67,	.mnemo="BIT 4, A"	},
	{	.opcode=0xCB60,	.mnemo="BIT 4, B"	},
	{	.opcode=0xCB61,	.mnemo="BIT 4, C"	},
	{	.opcode=0xCB62,	.mnemo="BIT 4, D"	},
	{	.opcode=0xCB63,	.mnemo="BIT 4, E"	},
	{	.opcode=0xCB64,	.mnemo="BIT 4, H"	},
	{	.opcode=0xCB65,	.mnemo="BIT 4, L"	},
	{	.opcode=0xCB6E,	.mnemo="BIT 5, [HL]"	},
	{	.opcode=0xDDCB6E,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB6C,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB6D,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB6F,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB6B,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB6A,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB69,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB68,	.mnemo="BIT 5, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB6E,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB6C,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB6D,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB6F,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB6A,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB6B,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB69,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB68,	.mnemo="BIT 5, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB6F,	.mnemo="BIT 5, A"	},
	{	.opcode=0xCB68,	.mnemo="BIT 5, B"	},
	{	.opcode=0xCB69,	.mnemo="BIT 5, C"	},
	{	.opcode=0xCB6A,	.mnemo="BIT 5, D"	},
	{	.opcode=0xCB6B,	.mnemo="BIT 5, E"	},
	{	.opcode=0xCB6C,	.mnemo="BIT 5, H"	},
	{	.opcode=0xCB6D,	.mnemo="BIT 5, L"	},
	{	.opcode=0xCB76,	.mnemo="BIT 6, [HL]"	},
	{	.opcode=0xDDCB76,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB74,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB75,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB77,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB72,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB73,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB71,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB70,	.mnemo="BIT 6, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB76,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB74,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB75,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB77,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB72,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB73,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB71,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB70,	.mnemo="BIT 6, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB77,	.mnemo="BIT 6, A"	},
	{	.opcode=0xCB70,	.mnemo="BIT 6, B"	},
	{	.opcode=0xCB71,	.mnemo="BIT 6, C"	},
	{	.opcode=0xCB72,	.mnemo="BIT 6, D"	},
	{	.opcode=0xCB73,	.mnemo="BIT 6, E"	},
	{	.opcode=0xCB74,	.mnemo="BIT 6, H"	},
	{	.opcode=0xCB75,	.mnemo="BIT 6, L"	},
	{	.opcode=0xCB7E,	.mnemo="BIT 7, [HL]"	},
	{	.opcode=0xDDCB7E,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB7C,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB7D,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB7F,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB7A,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB7B,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB79,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xDDCB78,	.mnemo="BIT 7, [IX + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB7E,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB7C,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB7D,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB7F,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB7A,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB7B,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB79,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xFDCB78,	.mnemo="BIT 7, [IY + %#.2x]",	.data_size=1,	.duplicate=true	},
	{	.opcode=0xCB7F,	.mnemo="BIT 7, A"	},
	{	.opcode=0xCB78,	.mnemo="BIT 7, B"	},
	{	.opcode=0xCB79,	.mnemo="BIT 7, C"	},
	{	.opcode=0xCB7A,	.mnemo="BIT 7, D"	},
	{	.opcode=0xCB7B,	.mnemo="BIT 7, E"	},
	{	.opcode=0xCB7C,	.mnemo="BIT 7, H"	},
	{	.opcode=0xCB7D,	.mnemo="BIT 7, L"	},
	{	.opcode=0xCD,	.mnemo="CALL %#.4x",	.data_size=2	},
	{	.opcode=0xDC,	.mnemo="CALL C, %#.4x",	.data_size=2	},
	{	.opcode=0xFC,	.mnemo="CALL M, %#.4x",	.data_size=2	},
	{	.opcode=0xD4,	.mnemo="CALL NC, %#.4x",	.data_size=2	},
	{	.opcode=0xC4,	.mnemo="CALL NZ, %#.4x",	.data_size=2	},
	{	.opcode=0xF4,	.mnemo="CALL P, %#.4x",	.data_size=2	},
	{	.opcode=0xEC,	.mnemo="CALL PE, %#.4x",	.data_size=2	},
	{	.opcode=0xE4,	.mnemo="CALL PO, %#.4x",	.data_size=2	},
	{	.opcode=0xCC,	.mnemo="CALL Z, %#.4x",	.data_size=2	},
	{	.opcode=0x3F,	.mnemo="CCF"	},
	{	.opcode=0xFE,	.mnemo="CP %#.2x",	.data_size=1	},
	{	.opcode=0xBE,	.mnemo="CP [HL]"	},
	{	.opcode=0xDDBE,	.mnemo="CP [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDBE,	.mnemo="CP [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xBF,	.mnemo="CP A"	},
	{	.opcode=0xB8,	.mnemo="CP B"	},
	{	.opcode=0xB9,	.mnemo="CP C"	},
	{	.opcode=0xBA,	.mnemo="CP D"	},
	{	.opcode=0xBB,	.mnemo="CP E"	},
	{	.opcode=0xBC,	.mnemo="CP H"	},
	{	.opcode=0xBD,	.mnemo="CP L"	},
	{	.opcode=0xDDBC,	.mnemo="CP XH"	},
	{	.opcode=0xDDBD,	.mnemo="CP XL"	},
	{	.opcode=0xFDBC,	.mnemo="CP YH"	},
	{	.opcode=0xFDBD,	.mnemo="CP YL"	},
	{	.opcode=0xEDA9,	.mnemo="CPD"	},
	{	.opcode=0xEDB9,	.mnemo="CPDR"	},
	{	.opcode=0xEDA1,	.mnemo="CPI"	},
	{	.opcode=0xEDB1,	.mnemo="CPIR"	},
	{	.opcode=0x2F,	.mnemo="CPL"	},
	{	.opcode=0x27,	.mnemo="DAA"	},
	{	.opcode=0x35,	.mnemo="DEC [HL]"	},
	{	.opcode=0xDD35,	.mnemo="DEC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD35,	.mnemo="DEC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x3D,	.mnemo="DEC A"	},
	{	.opcode=0x05,	.mnemo="DEC B"	},
	{	.opcode=0x0B,	.mnemo="DEC BC"	},
	{	.opcode=0x0D,	.mnemo="DEC C"	},
	{	.opcode=0x15,	.mnemo="DEC D"	},
	{	.opcode=0x1B,	.mnemo="DEC DE"	},
	{	.opcode=0x1D,	.mnemo="DEC E"	},
	{	.opcode=0x25,	.mnemo="DEC H"	},
	{	.opcode=0x2B,	.mnemo="DEC HL"	},
	{	.opcode=0xDD2B,	.mnemo="DEC IX"	},
	{	.opcode=0xFD2B,	.mnemo="DEC IY"	},
	{	.opcode=0x2D,	.mnemo="DEC L"	},
	{	.opcode=0x3B,	.mnemo="DEC SP"	},
	{	.opcode=0xDD25,	.mnemo="DEC XH"	},
	{	.opcode=0xDD2D,	.mnemo="DEC XL"	},
	{	.opcode=0xFD25,	.mnemo="DEC YH"	},
	{	.opcode=0xFD2D,	.mnemo="DEC YL"	},
	{	.opcode=0xF3,	.mnemo="DI"	},
	{	.opcode=0x10,	.mnemo="DJNZ %#.2x",	.data_size=1,	.reljmp=true	},
	{	.opcode=0xFB,	.mnemo="EI"	},
	{	.opcode=0xE3,	.mnemo="EX [SP], HL"	},
	{	.opcode=0xDDE3,	.mnemo="EX [SP], IX"	},
	{	.opcode=0xFDE3,	.mnemo="EX [SP], IY"	},
	{	.opcode=0x08,	.mnemo="EX AF, AF'"	},
	{	.opcode=0xEB,	.mnemo="EX DE, HL"	},
	{	.opcode=0xD9,	.mnemo="EXX"	},
	{	.opcode=0x76,	.mnemo="HALT"	},
	{	.opcode=0xED6E,	.mnemo="IM 0"	},
	{	.opcode=0xED66,	.mnemo="IM 0"	},
	{	.opcode=0xED4E,	.mnemo="IM 0"	},
	{	.opcode=0xED46,	.mnemo="IM 0"	},
	{	.opcode=0xED56,	.mnemo="IM 1"	},
	{	.opcode=0xED76,	.mnemo="IM 1",	.duplicate=true	},
	{	.opcode=0xED6E,	.mnemo="IM 1",	.duplicate=true	},
	{	.opcode=0xED4E,	.mnemo="IM 1",	.duplicate=true	},
	{	.opcode=0xED7E,	.mnemo="IM 2"	},
	{	.opcode=0xED5E,	.mnemo="IM 2"	},
	{	.opcode=0xED70,	.mnemo="IN [C], [C]"	},
	{	.opcode=0xDB,	.mnemo="IN A, [%#.2x]",	.data_size=1	},
	{	.opcode=0xED78,	.mnemo="IN A, [C]"	},
	{	.opcode=0xED40,	.mnemo="IN B, [C]"	},
	{	.opcode=0xED48,	.mnemo="IN C, [C]"	},
	{	.opcode=0xED50,	.mnemo="IN D, [C]"	},
	{	.opcode=0xED58,	.mnemo="IN E, [C]"	},
	{	.opcode=0xED70,	.mnemo="IN F, [C]"	},
	{	.opcode=0xED60,	.mnemo="IN H, [C]"	},
	{	.opcode=0xED68,	.mnemo="IN L, [C]"	},
	{	.opcode=0x34,	.mnemo="INC [HL]"	},
	{	.opcode=0xDD34,	.mnemo="INC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD34,	.mnemo="INC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x3C,	.mnemo="INC A"	},
	{	.opcode=0x04,	.mnemo="INC B"	},
	{	.opcode=0x03,	.mnemo="INC BC"	},
	{	.opcode=0x0C,	.mnemo="INC C"	},
	{	.opcode=0x14,	.mnemo="INC D"	},
	{	.opcode=0x13,	.mnemo="INC DE"	},
	{	.opcode=0x1C,	.mnemo="INC E"	},
	{	.opcode=0x24,	.mnemo="INC H"	},
	{	.opcode=0x23,	.mnemo="INC HL"	},
	{	.opcode=0xDD23,	.mnemo="INC IX"	},
	{	.opcode=0xFD23,	.mnemo="INC IY"	},
	{	.opcode=0x2C,	.mnemo="INC L"	},
	{	.opcode=0x33,	.mnemo="INC SP"	},
	{	.opcode=0xDD24,	.mnemo="INC XH"	},
	{	.opcode=0xDD2C,	.mnemo="INC XL"	},
	{	.opcode=0xFD24,	.mnemo="INC YH"	},
	{	.opcode=0xFD2C,	.mnemo="INC YL"	},
	{	.opcode=0xEDAA,	.mnemo="IND"	},
	{	.opcode=0xEDBA,	.mnemo="INDR"	},
	{	.opcode=0xEDA2,	.mnemo="INI"	},
	{	.opcode=0xEDB2,	.mnemo="INIR"	},
	{	.opcode=0xC3,	.mnemo="JP %#.4x",	.data_size=2	},
	{	.opcode=0xE9,	.mnemo="JP [HL]"	},
	{	.opcode=0xDDE9,	.mnemo="JP [IX]"	},
	{	.opcode=0xFDE9,	.mnemo="JP [IY]"	},
	{	.opcode=0xDA,	.mnemo="JP C, %#.4x",	.data_size=2	},
	{	.opcode=0xFA,	.mnemo="JP M, %#.4x",	.data_size=2	},
	{	.opcode=0xD2,	.mnemo="JP NC, %#.4x",	.data_size=2	},
	{	.opcode=0xC2,	.mnemo="JP NZ, %#.4x",	.data_size=2	},
	{	.opcode=0xF2,	.mnemo="JP P, %#.4x",	.data_size=2	},
	{	.opcode=0xEA,	.mnemo="JP PE, %#.4x",	.data_size=2	},
	{	.opcode=0xE2,	.mnemo="JP PO, %#.4x",	.data_size=2	},
	{	.opcode=0xCA,	.mnemo="JP Z, %#.4x",	.data_size=2	},
	{	.opcode=0x18,	.mnemo="JR %#.2x",	.data_size=1,	.reljmp=true	},
	{	.opcode=0x38,	.mnemo="JR C, %#.2x",	.data_size=1,	.reljmp=true	},
	{	.opcode=0x30,	.mnemo="JR NC, %#.2x",	.data_size=1,	.reljmp=true	},
	{	.opcode=0x20,	.mnemo="JR NZ, %#.2x",	.data_size=1,	.reljmp=true	},
	{	.opcode=0x28,	.mnemo="JR Z, %#.2x",	.data_size=1,	.reljmp=true	},
	{	.opcode=0x32,	.mnemo="LD [%#.4x], A",	.data_size=2	},
	{	.opcode=0xED43,	.mnemo="LD [%#.4x], BC",	.data_size=2	},
	{	.opcode=0xED53,	.mnemo="LD [%#.4x], DE",	.data_size=2	},
	{	.opcode=0x22,	.mnemo="LD [%#.4x], HL",	.data_size=2	},
	{	.opcode=0xED63,	.mnemo="LD [%#.4x], HL",	.data_size=2,	.duplicate=true	},
	{	.opcode=0xDD22,	.mnemo="LD [%#.4x], IX"	},
	{	.opcode=0xFD22,	.mnemo="LD [%#.4x], IY",	.data_size=2	},
	{	.opcode=0xED73,	.mnemo="LD [%#.4x], SP",	.data_size=2	},
	{	.opcode=0x02,	.mnemo="LD [BC], A"	},
	{	.opcode=0x12,	.mnemo="LD [DE], A"	},
	{	.opcode=0x36,	.mnemo="LD [HL], %#.2x",	.data_size=1	},
	{	.opcode=0x77,	.mnemo="LD [HL], A"	},
	{	.opcode=0x70,	.mnemo="LD [HL], B"	},
	{	.opcode=0x71,	.mnemo="LD [HL], C"	},
	{	.opcode=0x72,	.mnemo="LD [HL], D"	},
	{	.opcode=0x73,	.mnemo="LD [HL], E"	},
	{	.opcode=0x74,	.mnemo="LD [HL], H"	},
	{	.opcode=0x75,	.mnemo="LD [HL], L"	},
	{	.opcode=0xDD36,	.mnemo="LD [IX + %#.2x], %#.2x",	.data_size=1	},
	{	.opcode=0xDD77,	.mnemo="LD [IX + %#.2x], A",	.data_size=1	},
	{	.opcode=0xDD70,	.mnemo="LD [IX + %#.2x], B",	.data_size=1	},
	{	.opcode=0xDD71,	.mnemo="LD [IX + %#.2x], C",	.data_size=1	},
	{	.opcode=0xDD72,	.mnemo="LD [IX + %#.2x], D",	.data_size=1	},
	{	.opcode=0xDD73,	.mnemo="LD [IX + %#.2x], E",	.data_size=1	},
	{	.opcode=0xDD74,	.mnemo="LD [IX + %#.2x], H",	.data_size=1	},
	{	.opcode=0xDD75,	.mnemo="LD [IX + %#.2x], L",	.data_size=1	},
	{	.opcode=0xFD36,	.mnemo="LD [IY + %#.2x], %#.2x",	.data_size=1	},
	{	.opcode=0xFD77,	.mnemo="LD [IY + %#.2x], A",	.data_size=1	},
	{	.opcode=0xFD70,	.mnemo="LD [IY + %#.2x], B",	.data_size=1	},
	{	.opcode=0xFD71,	.mnemo="LD [IY + %#.2x], C",	.data_size=1	},
	{	.opcode=0xFD72,	.mnemo="LD [IY + %#.2x], D",	.data_size=1	},
	{	.opcode=0xFD73,	.mnemo="LD [IY + %#.2x], E",	.data_size=1	},
	{	.opcode=0xFD74,	.mnemo="LD [IY + %#.2x], H",	.data_size=1	},
	{	.opcode=0xFD75,	.mnemo="LD [IY + %#.2x], L",	.data_size=1	},
	{	.opcode=0x3E,	.mnemo="LD A, %#.2x",	.data_size=1	},
	{	.opcode=0x3A,	.mnemo="LD A, [%#.4x]",	.data_size=2	},
	{	.opcode=0x0A,	.mnemo="LD A, [BC]"	},
	{	.opcode=0x1A,	.mnemo="LD A, [DE]"	},
	{	.opcode=0x7E,	.mnemo="LD A, [HL]"	},
	{	.opcode=0xDD7E,	.mnemo="LD A, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD7E,	.mnemo="LD A, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x7F,	.mnemo="LD A, A"	},
	{	.opcode=0x78,	.mnemo="LD A, B"	},
	{	.opcode=0x79,	.mnemo="LD A, C"	},
	{	.opcode=0x7A,	.mnemo="LD A, D"	},
	{	.opcode=0x7B,	.mnemo="LD A, E"	},
	{	.opcode=0x7C,	.mnemo="LD A, H"	},
	{	.opcode=0xED57,	.mnemo="LD A, I"	},
	{	.opcode=0x7D,	.mnemo="LD A, L"	},
	{	.opcode=0xED5F,	.mnemo="LD A, R"	},
	{	.opcode=0xDDCB87,	.mnemo="LD A, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB87,	.mnemo="LD A, RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB8F,	.mnemo="LD A, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB8F,	.mnemo="LD A, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB97,	.mnemo="LD A, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB97,	.mnemo="LD A, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB9F,	.mnemo="LD A, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB9F,	.mnemo="LD A, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA7,	.mnemo="LD A, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA7,	.mnemo="LD A, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBAF,	.mnemo="LD A, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBAF,	.mnemo="LD A, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB7,	.mnemo="LD A, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB7,	.mnemo="LD A, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBBF,	.mnemo="LD A, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBBF,	.mnemo="LD A, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB17,	.mnemo="LD A, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB17,	.mnemo="LD A, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB07,	.mnemo="LD A, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB07,	.mnemo="LD A, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB1F,	.mnemo="LD A, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB1F,	.mnemo="LD A, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB0F,	.mnemo="LD A, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB0F,	.mnemo="LD A, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC7,	.mnemo="LD A, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC7,	.mnemo="LD A, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBCF,	.mnemo="LD A, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBCF,	.mnemo="LD A, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD7,	.mnemo="LD A, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD7,	.mnemo="LD A, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBDF,	.mnemo="LD A, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBDF,	.mnemo="LD A, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE7,	.mnemo="LD A, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE7,	.mnemo="LD A, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBEF,	.mnemo="LD A, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBEF,	.mnemo="LD A, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF7,	.mnemo="LD A, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF7,	.mnemo="LD A, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBFF,	.mnemo="LD A, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBFF,	.mnemo="LD A, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB27,	.mnemo="LD A, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB27,	.mnemo="LD A, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB37,	.mnemo="LD A, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB37,	.mnemo="LD A, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB2F,	.mnemo="LD A, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB2F,	.mnemo="LD A, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB3F,	.mnemo="LD A, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB3F,	.mnemo="LD A, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDD7C,	.mnemo="LD A, XH"	},
	{	.opcode=0xDD7D,	.mnemo="LD A, XL"	},
	{	.opcode=0xFD7C,	.mnemo="LD A, YH"	},
	{	.opcode=0xFD7D,	.mnemo="LD A, YL"	},
	{	.opcode=0x06,	.mnemo="LD B, %#.2x",	.data_size=1	},
	{	.opcode=0x46,	.mnemo="LD B, [HL]"	},
	{	.opcode=0xDD46,	.mnemo="LD B, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD46,	.mnemo="LD B, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x47,	.mnemo="LD B, A"	},
	{	.opcode=0x40,	.mnemo="LD B, B"	},
	{	.opcode=0x41,	.mnemo="LD B, C"	},
	{	.opcode=0x42,	.mnemo="LD B, D"	},
	{	.opcode=0x43,	.mnemo="LD B, E"	},
	{	.opcode=0x44,	.mnemo="LD B, H"	},
	{	.opcode=0x45,	.mnemo="LD B, L"	},
	{	.opcode=0xDDCB80,	.mnemo="LD B, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB80,	.mnemo="LD B, RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB88,	.mnemo="LD B, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB88,	.mnemo="LD B, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB90,	.mnemo="LD B, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB90,	.mnemo="LD B, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB98,	.mnemo="LD B, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB98,	.mnemo="LD B, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA0,	.mnemo="LD B, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA0,	.mnemo="LD B, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA8,	.mnemo="LD B, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA8,	.mnemo="LD B, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB0,	.mnemo="LD B, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB0,	.mnemo="LD B, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB8,	.mnemo="LD B, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB8,	.mnemo="LD B, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB10,	.mnemo="LD B, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB10,	.mnemo="LD B, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB00,	.mnemo="LD B, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB00,	.mnemo="LD B, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB18,	.mnemo="LD B, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB18,	.mnemo="LD B, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB08,	.mnemo="LD B, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB08,	.mnemo="LD B, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC0,	.mnemo="LD B, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC0,	.mnemo="LD B, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC8,	.mnemo="LD B, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC8,	.mnemo="LD B, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD0,	.mnemo="LD B, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD0,	.mnemo="LD B, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD8,	.mnemo="LD B, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD8,	.mnemo="LD B, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE0,	.mnemo="LD B, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE0,	.mnemo="LD B, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE8,	.mnemo="LD B, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE8,	.mnemo="LD B, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF0,	.mnemo="LD B, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF0,	.mnemo="LD B, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF8,	.mnemo="LD B, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF8,	.mnemo="LD B, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB20,	.mnemo="LD B, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB20,	.mnemo="LD B, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB30,	.mnemo="LD B, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB30,	.mnemo="LD B, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB28,	.mnemo="LD B, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB28,	.mnemo="LD B, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB38,	.mnemo="LD B, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB38,	.mnemo="LD B, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDD44,	.mnemo="LD B, XH"	},
	{	.opcode=0xDD45,	.mnemo="LD B, XL"	},
	{	.opcode=0xFD44,	.mnemo="LD B, YH"	},
	{	.opcode=0xFD45,	.mnemo="LD B, YL"	},
	{	.opcode=0x01,	.mnemo="LD BC, %#.4x",	.data_size=2	},
	{	.opcode=0xED4B,	.mnemo="LD BC, [%#.4x]",	.data_size=2	},
	{	.opcode=0x0E,	.mnemo="LD C, %#.2x",	.data_size=1	},
	{	.opcode=0x4E,	.mnemo="LD C, [HL]"	},
	{	.opcode=0xDD4E,	.mnemo="LD C, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD4E,	.mnemo="LD C, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x4F,	.mnemo="LD C, A"	},
	{	.opcode=0x48,	.mnemo="LD C, B"	},
	{	.opcode=0x49,	.mnemo="LD C, C"	},
	{	.opcode=0x4A,	.mnemo="LD C, D"	},
	{	.opcode=0x4B,	.mnemo="LD C, E"	},
	{	.opcode=0x4C,	.mnemo="LD C, H"	},
	{	.opcode=0x4D,	.mnemo="LD C, L"	},
	{	.opcode=0xDDCB81,	.mnemo="LD C, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB81,	.mnemo="LD C, RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB89,	.mnemo="LD C, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB89,	.mnemo="LD C, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB91,	.mnemo="LD C, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB91,	.mnemo="LD C, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB99,	.mnemo="LD C, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB99,	.mnemo="LD C, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA1,	.mnemo="LD C, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA1,	.mnemo="LD C, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA9,	.mnemo="LD C, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA9,	.mnemo="LD C, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB1,	.mnemo="LD C, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB1,	.mnemo="LD C, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB9,	.mnemo="LD C, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB9,	.mnemo="LD C, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB11,	.mnemo="LD C, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB11,	.mnemo="LD C, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB01,	.mnemo="LD C, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB01,	.mnemo="LD C, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB19,	.mnemo="LD C, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB19,	.mnemo="LD C, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB09,	.mnemo="LD C, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB09,	.mnemo="LD C, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC1,	.mnemo="LD C, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC1,	.mnemo="LD C, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC9,	.mnemo="LD C, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC9,	.mnemo="LD C, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD1,	.mnemo="LD C, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD1,	.mnemo="LD C, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD9,	.mnemo="LD C, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD9,	.mnemo="LD C, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE1,	.mnemo="LD C, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE1,	.mnemo="LD C, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE9,	.mnemo="LD C, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE9,	.mnemo="LD C, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF1,	.mnemo="LD C, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF1,	.mnemo="LD C, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF9,	.mnemo="LD C, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF9,	.mnemo="LD C, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB21,	.mnemo="LD C, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB21,	.mnemo="LD C, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB31,	.mnemo="LD C, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB31,	.mnemo="LD C, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB29,	.mnemo="LD C, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB29,	.mnemo="LD C, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB39,	.mnemo="LD C, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB39,	.mnemo="LD C, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDD4C,	.mnemo="LD C, XH"	},
	{	.opcode=0xDD4D,	.mnemo="LD C, XL"	},
	{	.opcode=0xFD4C,	.mnemo="LD C, YH"	},
	{	.opcode=0xFD4D,	.mnemo="LD C, YL"	},
	{	.opcode=0x16,	.mnemo="LD D, %#.2x",	.data_size=1	},
	{	.opcode=0x56,	.mnemo="LD D, [HL]"	},
	{	.opcode=0xDD56,	.mnemo="LD D, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD56,	.mnemo="LD D, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x57,	.mnemo="LD D, A"	},
	{	.opcode=0x50,	.mnemo="LD D, B"	},
	{	.opcode=0x51,	.mnemo="LD D, C"	},
	{	.opcode=0x52,	.mnemo="LD D, D"	},
	{	.opcode=0x53,	.mnemo="LD D, E"	},
	{	.opcode=0x54,	.mnemo="LD D, H"	},
	{	.opcode=0x55,	.mnemo="LD D, L"	},
	{	.opcode=0xDDCB82,	.mnemo="LD D, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB82,	.mnemo="LD D, RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB8A,	.mnemo="LD D, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB8A,	.mnemo="LD D, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB92,	.mnemo="LD D, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB92,	.mnemo="LD D, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB9A,	.mnemo="LD D, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB9A,	.mnemo="LD D, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA2,	.mnemo="LD D, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA2,	.mnemo="LD D, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBAA,	.mnemo="LD D, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBAA,	.mnemo="LD D, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB2,	.mnemo="LD D, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB2,	.mnemo="LD D, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBBA,	.mnemo="LD D, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBBA,	.mnemo="LD D, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB12,	.mnemo="LD D, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB12,	.mnemo="LD D, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB02,	.mnemo="LD D, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB02,	.mnemo="LD D, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB1A,	.mnemo="LD D, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB1A,	.mnemo="LD D, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB0A,	.mnemo="LD D, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB0A,	.mnemo="LD D, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC2,	.mnemo="LD D, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC2,	.mnemo="LD D, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBCA,	.mnemo="LD D, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBCA,	.mnemo="LD D, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD2,	.mnemo="LD D, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD2,	.mnemo="LD D, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBDA,	.mnemo="LD D, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBDA,	.mnemo="LD D, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE2,	.mnemo="LD D, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE2,	.mnemo="LD D, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBEA,	.mnemo="LD D, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBEA,	.mnemo="LD D, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF2,	.mnemo="LD D, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF2,	.mnemo="LD D, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBFA,	.mnemo="LD D, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBFA,	.mnemo="LD D, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB22,	.mnemo="LD D, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB22,	.mnemo="LD D, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB32,	.mnemo="LD D, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB32,	.mnemo="LD D, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB2A,	.mnemo="LD D, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB2A,	.mnemo="LD D, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB3A,	.mnemo="LD D, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB3A,	.mnemo="LD D, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDD54,	.mnemo="LD D, XH"	},
	{	.opcode=0xDD55,	.mnemo="LD D, XL"	},
	{	.opcode=0xFD54,	.mnemo="LD D, YH"	},
	{	.opcode=0xFD55,	.mnemo="LD D, YL"	},
	{	.opcode=0x11,	.mnemo="LD DE, %#.4x",	.data_size=2	},
	{	.opcode=0xED5B,	.mnemo="LD DE, [%#.4x]",	.data_size=2	},
	{	.opcode=0x1E,	.mnemo="LD E, %#.2x",	.data_size=1	},
	{	.opcode=0x5E,	.mnemo="LD E, [HL]"	},
	{	.opcode=0xDD5E,	.mnemo="LD E, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD5E,	.mnemo="LD E, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x5F,	.mnemo="LD E, A"	},
	{	.opcode=0x58,	.mnemo="LD E, B"	},
	{	.opcode=0x59,	.mnemo="LD E, C"	},
	{	.opcode=0x5A,	.mnemo="LD E, D"	},
	{	.opcode=0x5B,	.mnemo="LD E, E"	},
	{	.opcode=0x5C,	.mnemo="LD E, H"	},
	{	.opcode=0x5D,	.mnemo="LD E, L"	},
	{	.opcode=0xDDCB83,	.mnemo="LD E, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB8B,	.mnemo="LD E, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB8B,	.mnemo="LD E, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB93,	.mnemo="LD E, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB93,	.mnemo="LD E, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB9B,	.mnemo="LD E, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB9B,	.mnemo="LD E, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA3,	.mnemo="LD E, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA3,	.mnemo="LD E, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBAB,	.mnemo="LD E, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBAB,	.mnemo="LD E, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB3,	.mnemo="LD E, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB3,	.mnemo="LD E, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBBB,	.mnemo="LD E, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBBB,	.mnemo="LD E, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB13,	.mnemo="LD E, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB13,	.mnemo="LD E, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB03,	.mnemo="LD E, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB03,	.mnemo="LD E, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB1B,	.mnemo="LD E, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB1B,	.mnemo="LD E, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB0B,	.mnemo="LD E, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB0B,	.mnemo="LD E, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC3,	.mnemo="LD E, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC3,	.mnemo="LD E, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBCB,	.mnemo="LD E, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBCB,	.mnemo="LD E, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD3,	.mnemo="LD E, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD3,	.mnemo="LD E, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBDB,	.mnemo="LD E, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBDB,	.mnemo="LD E, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE3,	.mnemo="LD E, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE3,	.mnemo="LD E, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBEB,	.mnemo="LD E, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBEB,	.mnemo="LD E, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF3,	.mnemo="LD E, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF3,	.mnemo="LD E, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBFB,	.mnemo="LD E, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBFB,	.mnemo="LD E, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB23,	.mnemo="LD E, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB23,	.mnemo="LD E, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB33,	.mnemo="LD E, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB33,	.mnemo="LD E, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB2B,	.mnemo="LD E, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB2B,	.mnemo="LD E, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB3B,	.mnemo="LD E, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB3B,	.mnemo="LD E, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDD5C,	.mnemo="LD E, XH"	},
	{	.opcode=0xDD5D,	.mnemo="LD E, XL"	},
	{	.opcode=0xFD5C,	.mnemo="LD E, YH"	},
	{	.opcode=0xFD5D,	.mnemo="LD E, YL"	},
	{	.opcode=0x26,	.mnemo="LD H, %#.2x",	.data_size=1	},
	{	.opcode=0x66,	.mnemo="LD H, [HL]"	},
	{	.opcode=0xDD66,	.mnemo="LD H, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD66,	.mnemo="LD H, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x67,	.mnemo="LD H, A"	},
	{	.opcode=0x60,	.mnemo="LD H, B"	},
	{	.opcode=0x61,	.mnemo="LD H, C"	},
	{	.opcode=0x62,	.mnemo="LD H, D"	},
	{	.opcode=0x63,	.mnemo="LD H, E"	},
	{	.opcode=0x64,	.mnemo="LD H, H"	},
	{	.opcode=0x65,	.mnemo="LD H, L"	},
	{	.opcode=0xDDCB84,	.mnemo="LD H, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB84,	.mnemo="LD H, RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB8C,	.mnemo="LD H, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB8C,	.mnemo="LD H, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB94,	.mnemo="LD H, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB94,	.mnemo="LD H, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB9C,	.mnemo="LD H, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB9C,	.mnemo="LD H, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA4,	.mnemo="LD H, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA4,	.mnemo="LD H, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBAC,	.mnemo="LD H, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBAC,	.mnemo="LD H, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB4,	.mnemo="LD H, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB4,	.mnemo="LD H, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBBC,	.mnemo="LD H, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBBC,	.mnemo="LD H, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB14,	.mnemo="LD H, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB14,	.mnemo="LD H, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB04,	.mnemo="LD H, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB04,	.mnemo="LD H, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB1C,	.mnemo="LD H, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB1C,	.mnemo="LD H, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB0C,	.mnemo="LD H, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB0C,	.mnemo="LD H, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC4,	.mnemo="LD H, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC4,	.mnemo="LD H, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBCC,	.mnemo="LD H, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBCC,	.mnemo="LD H, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD4,	.mnemo="LD H, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD4,	.mnemo="LD H, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBDC,	.mnemo="LD H, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBDC,	.mnemo="LD H, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE4,	.mnemo="LD H, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE4,	.mnemo="LD H, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBEC,	.mnemo="LD H, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBEC,	.mnemo="LD H, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF4,	.mnemo="LD H, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF4,	.mnemo="LD H, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBFC,	.mnemo="LD H, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBFC,	.mnemo="LD H, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB24,	.mnemo="LD H, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB24,	.mnemo="LD H, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB34,	.mnemo="LD H, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB34,	.mnemo="LD H, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB2C,	.mnemo="LD H, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB2C,	.mnemo="LD H, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB3C,	.mnemo="LD H, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB3C,	.mnemo="LD H, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x21,	.mnemo="LD HL, %#.4x",	.data_size=2	},
	{	.opcode=0x2A,	.mnemo="LD HL, [%#.4x]",	.data_size=2	},
	{	.opcode=0xED6B,	.mnemo="LD HL, [%#.4x]",	.data_size=2,	.duplicate=true	},
	{	.opcode=0xED47,	.mnemo="LD I, A"	},
	{	.opcode=0xDD21,	.mnemo="LD IX, %#.4x",	.data_size=2	},
	{	.opcode=0xDD2A,	.mnemo="LD IX, [%#.4x]",	.data_size=2	},
	{	.opcode=0xFD21,	.mnemo="LD IY, %#.4x",	.data_size=2	},
	{	.opcode=0xFD2A,	.mnemo="LD IY, [%#.4x]",	.data_size=2	},
	{	.opcode=0x2E,	.mnemo="LD L, %#.2x",	.data_size=1	},
	{	.opcode=0x6E,	.mnemo="LD L, [HL]"	},
	{	.opcode=0xDD6E,	.mnemo="LD L, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD6E,	.mnemo="LD L, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x6F,	.mnemo="LD L, A"	},
	{	.opcode=0x68,	.mnemo="LD L, B"	},
	{	.opcode=0x69,	.mnemo="LD L, C"	},
	{	.opcode=0x6A,	.mnemo="LD L, D"	},
	{	.opcode=0x6B,	.mnemo="LD L, E"	},
	{	.opcode=0x6C,	.mnemo="LD L, H"	},
	{	.opcode=0x6D,	.mnemo="LD L, L"	},
	{	.opcode=0xDDCB85,	.mnemo="LD L, RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB85,	.mnemo="LD L, RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB8D,	.mnemo="LD L, RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB8D,	.mnemo="LD L, RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB95,	.mnemo="LD L, RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB95,	.mnemo="LD L, RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB9D,	.mnemo="LD L, RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB9D,	.mnemo="LD L, RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBA5,	.mnemo="LD L, RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA5,	.mnemo="LD L, RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBAD,	.mnemo="LD L, RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBAD,	.mnemo="LD L, RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBB5,	.mnemo="LD L, RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB5,	.mnemo="LD L, RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBBD,	.mnemo="LD L, RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBBD,	.mnemo="LD L, RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB15,	.mnemo="LD L, RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB15,	.mnemo="LD L, RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB05,	.mnemo="LD L, RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB05,	.mnemo="LD L, RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB1D,	.mnemo="LD L, RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB1D,	.mnemo="LD L, RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB0D,	.mnemo="LD L, RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB0D,	.mnemo="LD L, RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBC5,	.mnemo="LD L, SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC5,	.mnemo="LD L, SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBCD,	.mnemo="LD L, SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBCD,	.mnemo="LD L, SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBD5,	.mnemo="LD L, SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD5,	.mnemo="LD L, SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBDD,	.mnemo="LD L, SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBDD,	.mnemo="LD L, SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBE5,	.mnemo="LD L, SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE5,	.mnemo="LD L, SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBED,	.mnemo="LD L, SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBED,	.mnemo="LD L, SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBF5,	.mnemo="LD L, SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF5,	.mnemo="LD L, SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCBFD,	.mnemo="LD L, SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBFD,	.mnemo="LD L, SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB25,	.mnemo="LD L, SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB25,	.mnemo="LD L, SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB35,	.mnemo="LD L, SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB35,	.mnemo="LD L, SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB2D,	.mnemo="LD L, SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB2D,	.mnemo="LD L, SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xDDCB3D,	.mnemo="LD L, SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB3D,	.mnemo="LD L, SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xED4F,	.mnemo="LD R, A"	},
	{	.opcode=0x31,	.mnemo="LD SP, %#.4x",	.data_size=2	},
	{	.opcode=0xED7B,	.mnemo="LD SP, [%#.4x]",	.data_size=2	},
	{	.opcode=0xF9,	.mnemo="LD SP, HL"	},
	{	.opcode=0xDDF9,	.mnemo="LD SP, IX"	},
	{	.opcode=0xFDF9,	.mnemo="LD SP, IY"	},
	{	.opcode=0xDD26,	.mnemo="LD XH, %#.2x",	.data_size=1	},
	{	.opcode=0xDD67,	.mnemo="LD XH, A"	},
	{	.opcode=0xDD60,	.mnemo="LD XH, B"	},
	{	.opcode=0xDD61,	.mnemo="LD XH, C"	},
	{	.opcode=0xDD62,	.mnemo="LD XH, D"	},
	{	.opcode=0xDD63,	.mnemo="LD XH, E"	},
	{	.opcode=0xDD64,	.mnemo="LD XH, XH"	},
	{	.opcode=0xDD65,	.mnemo="LD XH, XL"	},
	{	.opcode=0xDD2E,	.mnemo="LD XL, %#.2x",	.data_size=1	},
	{	.opcode=0xDD6F,	.mnemo="LD XL, A"	},
	{	.opcode=0xDD68,	.mnemo="LD XL, B"	},
	{	.opcode=0xDD69,	.mnemo="LD XL, C"	},
	{	.opcode=0xDD6A,	.mnemo="LD XL, D"	},
	{	.opcode=0xDD6B,	.mnemo="LD XL, E"	},
	{	.opcode=0xDD6C,	.mnemo="LD XL, XH"	},
	{	.opcode=0xDD6D,	.mnemo="LD XL, XL"	},
	{	.opcode=0xFD26,	.mnemo="LD YH, %#.2x",	.data_size=1	},
	{	.opcode=0xFD67,	.mnemo="LD YH, A"	},
	{	.opcode=0xFD60,	.mnemo="LD YH, B"	},
	{	.opcode=0xFD61,	.mnemo="LD YH, C"	},
	{	.opcode=0xFD62,	.mnemo="LD YH, D"	},
	{	.opcode=0xFD63,	.mnemo="LD YH, E"	},
	{	.opcode=0xFD64,	.mnemo="LD YH, YH"	},
	{	.opcode=0xFD65,	.mnemo="LD YH, YL"	},
	{	.opcode=0xFD2E,	.mnemo="LD YL, %#.2x",	.data_size=1	},
	{	.opcode=0xFD6F,	.mnemo="LD YL, A"	},
	{	.opcode=0xFD68,	.mnemo="LD YL, B"	},
	{	.opcode=0xFD69,	.mnemo="LD YL, C"	},
	{	.opcode=0xFD6A,	.mnemo="LD YL, D"	},
	{	.opcode=0xFD6B,	.mnemo="LD YL, E"	},
	{	.opcode=0xFD6C,	.mnemo="LD YL, YH"	},
	{	.opcode=0xFD6D,	.mnemo="LD YL, YL"	},
	{	.opcode=0xEDA8,	.mnemo="LDD"	},
	{	.opcode=0xEDB8,	.mnemo="LDDR"	},
	{	.opcode=0xEDA0,	.mnemo="LDI"	},
	{	.opcode=0xEDB0,	.mnemo="LDIR"	},
	{	.opcode=0xED44,	.mnemo="NEG"	},
	{	.opcode=0xED6C,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0xED74,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0xED7C,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0xED5C,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0xED64,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0xED54,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0xED4C,	.mnemo="NEG",	.duplicate=true	},
	{	.opcode=0x00,	.mnemo="NOP"	},
	{	.opcode=0xF6,	.mnemo="OR %#.2x",	.data_size=1	},
	{	.opcode=0xB6,	.mnemo="OR [HL]"	},
	{	.opcode=0xDDB6,	.mnemo="OR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDB6,	.mnemo="OR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xB7,	.mnemo="OR A"	},
	{	.opcode=0xB0,	.mnemo="OR B"	},
	{	.opcode=0xB1,	.mnemo="OR C"	},
	{	.opcode=0xB2,	.mnemo="OR D"	},
	{	.opcode=0xB3,	.mnemo="OR E"	},
	{	.opcode=0xB4,	.mnemo="OR H"	},
	{	.opcode=0xB5,	.mnemo="OR L"	},
	{	.opcode=0xDDB4,	.mnemo="OR XH"	},
	{	.opcode=0xDDB5,	.mnemo="OR XL"	},
	{	.opcode=0xFDB4,	.mnemo="OR YH"	},
	{	.opcode=0xFDB5,	.mnemo="OR YL"	},
	{	.opcode=0xEDBB,	.mnemo="OTDR"	},
	{	.opcode=0xEDB3,	.mnemo="OTIR"	},
	{	.opcode=0xD3,	.mnemo="OUT [%#.2x], A"	},
	{	.opcode=0xED71,	.mnemo="OUT [C], 0"	},
	{	.opcode=0xED79,	.mnemo="OUT [C], A"	},
	{	.opcode=0xED41,	.mnemo="OUT [C], B"	},
	{	.opcode=0xED49,	.mnemo="OUT [C], C"	},
	{	.opcode=0xED51,	.mnemo="OUT [C], D"	},
	{	.opcode=0xED59,	.mnemo="OUT [C], E"	},
	{	.opcode=0xED61,	.mnemo="OUT [C], H"	},
	{	.opcode=0xED69,	.mnemo="OUT [C], L"	},
	{	.opcode=0xEDAB,	.mnemo="OUTD"	},
	{	.opcode=0xEDA3,	.mnemo="OUTI"	},
	{	.opcode=0xF1,	.mnemo="POP AF"	},
	{	.opcode=0xC1,	.mnemo="POP BC"	},
	{	.opcode=0xD1,	.mnemo="POP DE"	},
	{	.opcode=0xE1,	.mnemo="POP HL"	},
	{	.opcode=0xDDE1,	.mnemo="POP IX"	},
	{	.opcode=0xFDE1,	.mnemo="POP IY"	},
	{	.opcode=0xF5,	.mnemo="PUSH AF"	},
	{	.opcode=0xC5,	.mnemo="PUSH BC"	},
	{	.opcode=0xD5,	.mnemo="PUSH DE"	},
	{	.opcode=0xE5,	.mnemo="PUSH HL"	},
	{	.opcode=0xDDE5,	.mnemo="PUSH IX"	},
	{	.opcode=0xFDE5,	.mnemo="PUSH IY"	},
	{	.opcode=0xCB86,	.mnemo="RES 0, [HL]"	},
	{	.opcode=0xDDCB86,	.mnemo="RES 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB86,	.mnemo="RES 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB87,	.mnemo="RES 0, A"	},
	{	.opcode=0xCB80,	.mnemo="RES 0, B"	},
	{	.opcode=0xCB81,	.mnemo="RES 0, C"	},
	{	.opcode=0xCB82,	.mnemo="RES 0, D"	},
	{	.opcode=0xCB83,	.mnemo="RES 0, E"	},
	{	.opcode=0xCB84,	.mnemo="RES 0, H"	},
	{	.opcode=0xCB85,	.mnemo="RES 0, L"	},
	{	.opcode=0xCB8E,	.mnemo="RES 1, [HL]"	},
	{	.opcode=0xDDCB8E,	.mnemo="RES 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB8E,	.mnemo="RES 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB8F,	.mnemo="RES 1, A"	},
	{	.opcode=0xCB88,	.mnemo="RES 1, B"	},
	{	.opcode=0xCB89,	.mnemo="RES 1, C"	},
	{	.opcode=0xCB8A,	.mnemo="RES 1, D"	},
	{	.opcode=0xCB8B,	.mnemo="RES 1, E"	},
	{	.opcode=0xCB8C,	.mnemo="RES 1, H"	},
	{	.opcode=0xCB8D,	.mnemo="RES 1, L"	},
	{	.opcode=0xCB96,	.mnemo="RES 2, [HL]"	},
	{	.opcode=0xDDCB96,	.mnemo="RES 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB96,	.mnemo="RES 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB97,	.mnemo="RES 2, A"	},
	{	.opcode=0xCB90,	.mnemo="RES 2, B"	},
	{	.opcode=0xCB91,	.mnemo="RES 2, C"	},
	{	.opcode=0xCB92,	.mnemo="RES 2, D"	},
	{	.opcode=0xCB93,	.mnemo="RES 2, E"	},
	{	.opcode=0xCB94,	.mnemo="RES 2, H"	},
	{	.opcode=0xCB95,	.mnemo="RES 2, L"	},
	{	.opcode=0xCB9E,	.mnemo="RES 3, [HL]"	},
	{	.opcode=0xDDCB9E,	.mnemo="RES 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB9E,	.mnemo="RES 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB9F,	.mnemo="RES 3, A"	},
	{	.opcode=0xCB98,	.mnemo="RES 3, B"	},
	{	.opcode=0xCB99,	.mnemo="RES 3, C"	},
	{	.opcode=0xCB9A,	.mnemo="RES 3, D"	},
	{	.opcode=0xCB9B,	.mnemo="RES 3, E"	},
	{	.opcode=0xCB9C,	.mnemo="RES 3, H"	},
	{	.opcode=0xCB9D,	.mnemo="RES 3, L"	},
	{	.opcode=0xCBA6,	.mnemo="RES 4, [HL]"	},
	{	.opcode=0xDDCBA6,	.mnemo="RES 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBA6,	.mnemo="RES 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBA7,	.mnemo="RES 4, A"	},
	{	.opcode=0xCBA0,	.mnemo="RES 4, B"	},
	{	.opcode=0xCBA1,	.mnemo="RES 4, C"	},
	{	.opcode=0xCBA2,	.mnemo="RES 4, D"	},
	{	.opcode=0xCBA3,	.mnemo="RES 4, E"	},
	{	.opcode=0xCBA4,	.mnemo="RES 4, H"	},
	{	.opcode=0xCBA5,	.mnemo="RES 4, L"	},
	{	.opcode=0xCBAE,	.mnemo="RES 5, [HL]"	},
	{	.opcode=0xDDCBAE,	.mnemo="RES 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBAE,	.mnemo="RES 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBAF,	.mnemo="RES 5, A"	},
	{	.opcode=0xCBA8,	.mnemo="RES 5, B"	},
	{	.opcode=0xCBA9,	.mnemo="RES 5, C"	},
	{	.opcode=0xCBAA,	.mnemo="RES 5, D"	},
	{	.opcode=0xCBAB,	.mnemo="RES 5, E"	},
	{	.opcode=0xCBAC,	.mnemo="RES 5, H"	},
	{	.opcode=0xCBAD,	.mnemo="RES 5, L"	},
	{	.opcode=0xCBB6,	.mnemo="RES 6, [HL]"	},
	{	.opcode=0xDDCBB6,	.mnemo="RES 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBB6,	.mnemo="RES 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBB7,	.mnemo="RES 6, A"	},
	{	.opcode=0xCBB0,	.mnemo="RES 6, B"	},
	{	.opcode=0xCBB1,	.mnemo="RES 6, C"	},
	{	.opcode=0xCBB2,	.mnemo="RES 6, D"	},
	{	.opcode=0xCBB3,	.mnemo="RES 6, E"	},
	{	.opcode=0xCBB4,	.mnemo="RES 6, H"	},
	{	.opcode=0xCBB5,	.mnemo="RES 6, L"	},
	{	.opcode=0xCBBE,	.mnemo="RES 7, [HL]"	},
	{	.opcode=0xDDCBBE,	.mnemo="RES 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBBE,	.mnemo="RES 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBBF,	.mnemo="RES 7, A"	},
	{	.opcode=0xCBB8,	.mnemo="RES 7, B"	},
	{	.opcode=0xCBB9,	.mnemo="RES 7, C"	},
	{	.opcode=0xCBBA,	.mnemo="RES 7, D"	},
	{	.opcode=0xCBBB,	.mnemo="RES 7, E"	},
	{	.opcode=0xCBBC,	.mnemo="RES 7, H"	},
	{	.opcode=0xCBBD,	.mnemo="RES 7, L"	},
	{	.opcode=0xC9,	.mnemo="RET"	},
	{	.opcode=0xD8,	.mnemo="RET C"	},
	{	.opcode=0xF8,	.mnemo="RET M"	},
	{	.opcode=0xD0,	.mnemo="RET NC"	},
	{	.opcode=0xC0,	.mnemo="RET NZ"	},
	{	.opcode=0xF0,	.mnemo="RET P"	},
	{	.opcode=0xE8,	.mnemo="RET PE"	},
	{	.opcode=0xE0,	.mnemo="RET PO"	},
	{	.opcode=0xC8,	.mnemo="RET Z"	},
	{	.opcode=0xED4D,	.mnemo="RETI"	},
	{	.opcode=0xED45,	.mnemo="RETN"	},
	{	.opcode=0xED7D,	.mnemo="RETN",	.duplicate=true	},
	{	.opcode=0xED6D,	.mnemo="RETN",	.duplicate=true	},
	{	.opcode=0xED75,	.mnemo="RETN",	.duplicate=true	},
	{	.opcode=0xED65,	.mnemo="RETN",	.duplicate=true	},
	{	.opcode=0xED5D,	.mnemo="RETN",	.duplicate=true	},
	{	.opcode=0xED55,	.mnemo="RETN",	.duplicate=true	},
	{	.opcode=0xCB16,	.mnemo="RL [HL]"	},
	{	.opcode=0xDDCB16,	.mnemo="RL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB16,	.mnemo="RL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB17,	.mnemo="RL A"	},
	{	.opcode=0xCB10,	.mnemo="RL B"	},
	{	.opcode=0xCB11,	.mnemo="RL C"	},
	{	.opcode=0xCB12,	.mnemo="RL D"	},
	{	.opcode=0xCB13,	.mnemo="RL E"	},
	{	.opcode=0xCB14,	.mnemo="RL H"	},
	{	.opcode=0xCB15,	.mnemo="RL L"	},
	{	.opcode=0x17,	.mnemo="RLA"	},
	{	.opcode=0xCB06,	.mnemo="RLC [HL]"	},
	{	.opcode=0xDDCB06,	.mnemo="RLC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB06,	.mnemo="RLC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB07,	.mnemo="RLC A"	},
	{	.opcode=0xCB00,	.mnemo="RLC B"	},
	{	.opcode=0xCB01,	.mnemo="RLC C"	},
	{	.opcode=0xCB02,	.mnemo="RLC D"	},
	{	.opcode=0xCB03,	.mnemo="RLC E"	},
	{	.opcode=0xCB04,	.mnemo="RLC H"	},
	{	.opcode=0xCB05,	.mnemo="RLC L"	},
	{	.opcode=0x07,	.mnemo="RLCA"	},
	{	.opcode=0xED6F,	.mnemo="RLD"	},
	{	.opcode=0xCB1E,	.mnemo="RR [HL]"	},
	{	.opcode=0xDDCB1E,	.mnemo="RR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB1E,	.mnemo="RR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB1F,	.mnemo="RR A"	},
	{	.opcode=0xCB18,	.mnemo="RR B"	},
	{	.opcode=0xCB19,	.mnemo="RR C"	},
	{	.opcode=0xCB1A,	.mnemo="RR D"	},
	{	.opcode=0xCB1B,	.mnemo="RR E"	},
	{	.opcode=0xCB1C,	.mnemo="RR H"	},
	{	.opcode=0xCB1D,	.mnemo="RR L"	},
	{	.opcode=0x1F,	.mnemo="RRA"	},
	{	.opcode=0xCB0E,	.mnemo="RRC [HL]"	},
	{	.opcode=0xDDCB0E,	.mnemo="RRC [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB0E,	.mnemo="RRC [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB0F,	.mnemo="RRC A"	},
	{	.opcode=0xCB08,	.mnemo="RRC B"	},
	{	.opcode=0xCB09,	.mnemo="RRC C"	},
	{	.opcode=0xCB0A,	.mnemo="RRC D"	},
	{	.opcode=0xCB0B,	.mnemo="RRC E"	},
	{	.opcode=0xCB0C,	.mnemo="RRC H"	},
	{	.opcode=0xCB0D,	.mnemo="RRC L"	},
	{	.opcode=0x0F,	.mnemo="RRCA"	},
	{	.opcode=0xED67,	.mnemo="RRD"	},
	{	.opcode=0xC7,	.mnemo="RST 0"	},
	{	.opcode=0xD7,	.mnemo="RST 10"	},
	{	.opcode=0xF7,	.mnemo="RST 16"	},
	{	.opcode=0xDF,	.mnemo="RST 18"	},
	{	.opcode=0xE7,	.mnemo="RST 20"	},
	{	.opcode=0xF7,	.mnemo="RST 24"	},
	{	.opcode=0xEF,	.mnemo="RST 28"	},
	{	.opcode=0xF7,	.mnemo="RST 30"	},
	{	.opcode=0xF7,	.mnemo="RST 32"	},
	{	.opcode=0xFF,	.mnemo="RST 38"	},
	{	.opcode=0xF7,	.mnemo="RST 40"	},
	{	.opcode=0xF7,	.mnemo="RST 48"	},
	{	.opcode=0xFF,	.mnemo="RST 56"	},
	{	.opcode=0xCF,	.mnemo="RST 8"	},
	{	.opcode=0xDE,	.mnemo="SBC A, %#.2x",	.data_size=1	},
	{	.opcode=0x9E,	.mnemo="SBC A, [HL]"	},
	{	.opcode=0xDD9E,	.mnemo="SBC A, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD9E,	.mnemo="SBC A, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x9F,	.mnemo="SBC A, A"	},
	{	.opcode=0x98,	.mnemo="SBC A, B"	},
	{	.opcode=0x99,	.mnemo="SBC A, C"	},
	{	.opcode=0x9A,	.mnemo="SBC A, D"	},
	{	.opcode=0x9B,	.mnemo="SBC A, E"	},
	{	.opcode=0x9C,	.mnemo="SBC A, H"	},
	{	.opcode=0x9D,	.mnemo="SBC A, L"	},
	{	.opcode=0xDD9C,	.mnemo="SBC A, XH"	},
	{	.opcode=0xDD9D,	.mnemo="SBC A, XL"	},
	{	.opcode=0xFD9C,	.mnemo="SBC A, YH"	},
	{	.opcode=0xFD9D,	.mnemo="SBC A, YL"	},
	{	.opcode=0xED42,	.mnemo="SBC HL, BC"	},
	{	.opcode=0xED52,	.mnemo="SBC HL, DE"	},
	{	.opcode=0xED62,	.mnemo="SBC HL, HL"	},
	{	.opcode=0xED72,	.mnemo="SBC HL, SP"	},
	{	.opcode=0x37,	.mnemo="SCF"	},
	{	.opcode=0xCBC6,	.mnemo="SET 0, [HL]"	},
	{	.opcode=0xDDCBC6,	.mnemo="SET 0, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBC6,	.mnemo="SET 0, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBC7,	.mnemo="SET 0, A"	},
	{	.opcode=0xCBC0,	.mnemo="SET 0, B"	},
	{	.opcode=0xCBC1,	.mnemo="SET 0, C"	},
	{	.opcode=0xCBC2,	.mnemo="SET 0, D"	},
	{	.opcode=0xCBC3,	.mnemo="SET 0, E"	},
	{	.opcode=0xCBC4,	.mnemo="SET 0, H"	},
	{	.opcode=0xCBC5,	.mnemo="SET 0, L"	},
	{	.opcode=0xCBCE,	.mnemo="SET 1, [HL]"	},
	{	.opcode=0xDDCBCE,	.mnemo="SET 1, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBCE,	.mnemo="SET 1, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBCF,	.mnemo="SET 1, A"	},
	{	.opcode=0xCBC8,	.mnemo="SET 1, B"	},
	{	.opcode=0xCBC9,	.mnemo="SET 1, C"	},
	{	.opcode=0xCBCA,	.mnemo="SET 1, D"	},
	{	.opcode=0xCBCB,	.mnemo="SET 1, E"	},
	{	.opcode=0xCBCC,	.mnemo="SET 1, H"	},
	{	.opcode=0xCBCD,	.mnemo="SET 1, L"	},
	{	.opcode=0xCBD6,	.mnemo="SET 2, [HL]"	},
	{	.opcode=0xDDCBD6,	.mnemo="SET 2, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBD6,	.mnemo="SET 2, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBD7,	.mnemo="SET 2, A"	},
	{	.opcode=0xCBD0,	.mnemo="SET 2, B"	},
	{	.opcode=0xCBD1,	.mnemo="SET 2, C"	},
	{	.opcode=0xCBD2,	.mnemo="SET 2, D"	},
	{	.opcode=0xCBD3,	.mnemo="SET 2, E"	},
	{	.opcode=0xCBD4,	.mnemo="SET 2, H"	},
	{	.opcode=0xCBD5,	.mnemo="SET 2, L"	},
	{	.opcode=0xCBDE,	.mnemo="SET 3, [HL]"	},
	{	.opcode=0xDDCBDE,	.mnemo="SET 3, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBDE,	.mnemo="SET 3, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBDF,	.mnemo="SET 3, A"	},
	{	.opcode=0xCBD8,	.mnemo="SET 3, B"	},
	{	.opcode=0xCBD9,	.mnemo="SET 3, C"	},
	{	.opcode=0xCBDA,	.mnemo="SET 3, D"	},
	{	.opcode=0xCBDB,	.mnemo="SET 3, E"	},
	{	.opcode=0xCBDC,	.mnemo="SET 3, H"	},
	{	.opcode=0xCBDD,	.mnemo="SET 3, L"	},
	{	.opcode=0xCBE6,	.mnemo="SET 4, [HL]"	},
	{	.opcode=0xDDCBE6,	.mnemo="SET 4, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBE6,	.mnemo="SET 4, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBE7,	.mnemo="SET 4, A"	},
	{	.opcode=0xCBE0,	.mnemo="SET 4, B"	},
	{	.opcode=0xCBE1,	.mnemo="SET 4, C"	},
	{	.opcode=0xCBE2,	.mnemo="SET 4, D"	},
	{	.opcode=0xCBE3,	.mnemo="SET 4, E"	},
	{	.opcode=0xCBE4,	.mnemo="SET 4, H"	},
	{	.opcode=0xCBE5,	.mnemo="SET 4, L"	},
	{	.opcode=0xCBEE,	.mnemo="SET 5, [HL]"	},
	{	.opcode=0xDDCBEE,	.mnemo="SET 5, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBEE,	.mnemo="SET 5, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBEF,	.mnemo="SET 5, A"	},
	{	.opcode=0xCBE8,	.mnemo="SET 5, B"	},
	{	.opcode=0xCBE9,	.mnemo="SET 5, C"	},
	{	.opcode=0xCBEA,	.mnemo="SET 5, D"	},
	{	.opcode=0xCBEB,	.mnemo="SET 5, E"	},
	{	.opcode=0xCBEC,	.mnemo="SET 5, H"	},
	{	.opcode=0xCBED,	.mnemo="SET 5, L"	},
	{	.opcode=0xCBF6,	.mnemo="SET 6, [HL]"	},
	{	.opcode=0xDDCBF6,	.mnemo="SET 6, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBF6,	.mnemo="SET 6, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBF7,	.mnemo="SET 6, A"	},
	{	.opcode=0xCBF0,	.mnemo="SET 6, B"	},
	{	.opcode=0xCBF1,	.mnemo="SET 6, C"	},
	{	.opcode=0xCBF2,	.mnemo="SET 6, D"	},
	{	.opcode=0xCBF3,	.mnemo="SET 6, E"	},
	{	.opcode=0xCBF4,	.mnemo="SET 6, H"	},
	{	.opcode=0xCBF5,	.mnemo="SET 6, L"	},
	{	.opcode=0xCBFE,	.mnemo="SET 7, [HL]"	},
	{	.opcode=0xDDCBFE,	.mnemo="SET 7, [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCBFE,	.mnemo="SET 7, [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCBFF,	.mnemo="SET 7, A"	},
	{	.opcode=0xCBF8,	.mnemo="SET 7, B"	},
	{	.opcode=0xCBF9,	.mnemo="SET 7, C"	},
	{	.opcode=0xCBFA,	.mnemo="SET 7, D"	},
	{	.opcode=0xCBFB,	.mnemo="SET 7, E"	},
	{	.opcode=0xCBFC,	.mnemo="SET 7, H"	},
	{	.opcode=0xCBFD,	.mnemo="SET 7, L"	},
	{	.opcode=0xCB26,	.mnemo="SLA [HL]"	},
	{	.opcode=0xDDCB26,	.mnemo="SLA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB26,	.mnemo="SLA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB27,	.mnemo="SLA A"	},
	{	.opcode=0xCB20,	.mnemo="SLA B"	},
	{	.opcode=0xCB21,	.mnemo="SLA C"	},
	{	.opcode=0xCB22,	.mnemo="SLA D"	},
	{	.opcode=0xCB23,	.mnemo="SLA E"	},
	{	.opcode=0xCB24,	.mnemo="SLA H"	},
	{	.opcode=0xCB25,	.mnemo="SLA L"	},
	{	.opcode=0xCB36,	.mnemo="SLL [HL]"	},
	{	.opcode=0xDDCB36,	.mnemo="SLL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB36,	.mnemo="SLL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB37,	.mnemo="SLL A"	},
	{	.opcode=0xCB30,	.mnemo="SLL B"	},
	{	.opcode=0xCB31,	.mnemo="SLL C"	},
	{	.opcode=0xCB32,	.mnemo="SLL D"	},
	{	.opcode=0xCB33,	.mnemo="SLL E"	},
	{	.opcode=0xCB34,	.mnemo="SLL H"	},
	{	.opcode=0xCB35,	.mnemo="SLL L"	},
	{	.opcode=0xCB2E,	.mnemo="SRA [HL]"	},
	{	.opcode=0xDDCB2E,	.mnemo="SRA [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB2E,	.mnemo="SRA [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB2F,	.mnemo="SRA A"	},
	{	.opcode=0xCB28,	.mnemo="SRA B"	},
	{	.opcode=0xCB29,	.mnemo="SRA C"	},
	{	.opcode=0xCB2A,	.mnemo="SRA D"	},
	{	.opcode=0xCB2B,	.mnemo="SRA E"	},
	{	.opcode=0xCB2C,	.mnemo="SRA H"	},
	{	.opcode=0xCB2D,	.mnemo="SRA L"	},
	{	.opcode=0xCB3E,	.mnemo="SRL [HL]"	},
	{	.opcode=0xDDCB3E,	.mnemo="SRL [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDCB3E,	.mnemo="SRL [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xCB3F,	.mnemo="SRL A"	},
	{	.opcode=0xCB38,	.mnemo="SRL B"	},
	{	.opcode=0xCB39,	.mnemo="SRL C"	},
	{	.opcode=0xCB3A,	.mnemo="SRL D"	},
	{	.opcode=0xCB3B,	.mnemo="SRL E"	},
	{	.opcode=0xCB3C,	.mnemo="SRL H"	},
	{	.opcode=0xCB3D,	.mnemo="SRL L"	},
	{	.opcode=0xD6,	.mnemo="SUB %#.2x",	.data_size=1	},
	{	.opcode=0x96,	.mnemo="SUB [HL]"	},
	{	.opcode=0xDD96,	.mnemo="SUB [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFD96,	.mnemo="SUB [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0x97,	.mnemo="SUB A"	},
	{	.opcode=0x90,	.mnemo="SUB B"	},
	{	.opcode=0x91,	.mnemo="SUB C"	},
	{	.opcode=0x92,	.mnemo="SUB D"	},
	{	.opcode=0x93,	.mnemo="SUB E"	},
	{	.opcode=0x94,	.mnemo="SUB H"	},
	{	.opcode=0x95,	.mnemo="SUB L"	},
	{	.opcode=0xDD94,	.mnemo="SUB XH"	},
	{	.opcode=0xDD95,	.mnemo="SUB XL"	},
	{	.opcode=0xFD94,	.mnemo="SUB YH"	},
	{	.opcode=0xFD95,	.mnemo="SUB YL"	},
	{	.opcode=0xEE,	.mnemo="XOR %#.2x",	.data_size=1	},
	{	.opcode=0xAE,	.mnemo="XOR [HL]"	},
	{	.opcode=0xDDAE,	.mnemo="XOR [IX + %#.2x]",	.data_size=1	},
	{	.opcode=0xFDAE,	.mnemo="XOR [IY + %#.2x]",	.data_size=1	},
	{	.opcode=0xAF,	.mnemo="XOR A"	},
	{	.opcode=0xA8,	.mnemo="XOR B"	},
	{	.opcode=0xA9,	.mnemo="XOR C"	},
	{	.opcode=0xAA,	.mnemo="XOR D"	},
	{	.opcode=0xAB,	.mnemo="XOR E"	},
	{	.opcode=0xAC,	.mnemo="XOR H"	},
	{	.opcode=0xAD,	.mnemo="XOR L"	},
	{	.opcode=0xDDAC,	.mnemo="XOR XH"	},
	{	.opcode=0xDDAD,	.mnemo="XOR XL"	},
	{	.opcode=0xFDAC,	.mnemo="XOR YH"	},
	{	.opcode=0xFDAD,	.mnemo="XOR YL"	},
	{	0,	0	}
};

/* without null terminated entry */
const int opcode_tab_count = (sizeof( opcode_tab )/(sizeof(opcode_tab[0])))-1;

