language: c
include:
  # cross-compile using mingw 
  - compiler: ": w32"
    env: PLATFORM="mingw32" ARCH="x86" BITSIZE=32 HOST="i686"

install:
 - sudo apt-get update -qq
 - sudo apt-get install -y mingw32-binutils mingw32 mingw32-runtime bison flex lua5.3

script:
 - make
 - make test

